Support for Sybase ASE and Informix
cmu-db/benchbase pull request #349
Opened 2023-08-23 13:52 UTC by anasY2

2023-09-12 02:34 UTC, apavlo requested changes
@anasY2 Thank you for submitting this. Please see my comments about your commits.

Is there a way for us to add this to our CI tests with a Docker installation of Informix/Sybase? It would be nice to know that we can maintain compatibility with these systems over the years.

2023-09-12 02:34 UTC, apavlo commented on src/main/java/com/oltpbenchmark/benchmarks/tpcc/TPCCLoader.java
What changed in this file other than whitespace?

2023-09-12 02:34 UTC, apavlo commented on src/main/java/com/oltpbenchmark/benchmarks/ycsb/YCSBBenchmark.java
> +            String userCount = SQLUtil.getMaxColSQL(this.workConf.getDatabaseType(), t, "YCSB_KEY");
Is this change specific to Informix?

2023-09-12 02:34 UTC, apavlo commented on src/main/java/com/oltpbenchmark/types/DatabaseType.java
> +    POSTGRES(false, false),
Why did you change Postgres?

2023-09-12 02:34 UTC, apavlo commented on src/main/java/com/oltpbenchmark/types/DatabaseType.java
> +    SQLSERVER(true, false),
Why did you change SQLSERVER?

2023-09-12 02:34 UTC, apavlo commented on src/main/resources/benchmarks/tatp/ddl-sqlserver.sql
Why did you change syntax case?

2023-09-12 02:34 UTC, apavlo commented on src/main/resources/benchmarks/tpcc/ddl-sqlserver.sql
Why did you change syntax case?

2023-09-12 02:34 UTC, apavlo commented on src/main/resources/benchmarks/voter/ddl-sqlserver.sql
Again, these changes seem unnecessary.

2023-09-12 02:34 UTC, apavlo commented on src/main/resources/benchmarks/ycsb/ddl-sqlserver.sql
Unnecessary case changes. Please revert.

2023-09-12 02:34 UTC, apavlo commented on src/main/resources/logging.properties
Please don't include this change. It's only for local dev debugging.

2023-09-12 02:34 UTC, apavlo commented on pom-arcion.xml
What is this file?

2023-09-25 11:13 UTC, anasY2 commented
@apavlo I will correct the things you have mentioned and will make a new PR.
Thankyou for suggestions :).

2023-09-25 11:19 UTC, closed without merging